### ISSUE TITLE
Pipe name constraint

### ISSUE THREAD

**Issue by kmannislands** [dcharbonnier/hydrated-ws#103]
Seems that pipes have an (undocumented) constraint that names can't be more than 4 characters. 

This makes sense knowing a little bit about the implementation of the library (there's a real cost to making the delimiters too long, which I assume motivates this constraint). It seems however that this pushes a lot of complexity onto the user to make sure that channel names are short enough, don't collide, etc.

It would be ideal if any arbitrary-length string could be used as a channel name and if `hydrated-ws` internally kept a mapping of 'channel names I've seen so far' to 'smallest possible string representation'. This would simplify the user-interface and enable `hydrated-ws` to control the string representations more efficiently.

Of course, it's possible to do this mapping outside of `hydrated-ws` and to pass those values in, but in doing so, it became obvious that a 6 character limit would be a lot more ergonomic since most common arbitrary string hashing libraries will give back a 10 digit int which can be mapped to a 6 digit string. [Example](https://runkit.com/kmannislands/5b7f3bbb9f011600124a0e26)

Would you be open to a PR to support arbitrary strings as a channel name? Or if not, can max length be made configurable/raised to 6 chars?

**Comment by dcharbonnier** [comment]
it's an arbitrary limit and my initial intention was to allow to setup this limit, I would be happy to have a PR that document and allow to setup this limit, I would keep 4 by default to avoid breaking compatibility.
