### ISSUE TITLE
Async URL generator failure

### ISSUE THREAD

**Issue by JanMatas** [dcharbonnier/hydrated-ws#210]
Hi, 

first of all, thanks for the awesome WS library! 

I am running into an issue with new feature: asyncUrlGenerator, more specifically I am struggling to handle situations when async url generation fails. Looking at your tests, it seems like the intended api would be to return "unknown" as url in case of failure and let the websocket fail to connect.

I would suggest to instead retry according to the retry policy immediately after urlGenerator throws. Code change would be IMHO trivial. Change line 255 from:

`urlOrPromise.then ? urlOrPromise.then(doOpen) : doOpen(urlOrPromise);`      

`urlOrPromise.then ? urlOrPromise.then(doOpen).catch(this.failed) : doOpen(urlOrPromise);`  

Let me know if you agree with proposed API change, happy to make PR if it helps.

**Comment by dcharbonnier** [comment]
I definitely agree with this change and would be happy to get a PR !

**Comment by dcharbonnier** [comment]
close https://github.com/dcharbonnier/hydrated-ws/pull/211

**Comment by dcharbonnier** [comment]
release 1.2.3 @JanMatas thanks again
